---
site_name: "oae-data-protocol"
theme:
  name: material
  # palette:
  #  scheme: slate
  #  primary: cyan
  features:
    - content.tabs.link
plugins:
  - search
  - mermaid2
  - mknotebooks:
      execute: false
  - mermaid2:
      version: 10.9.0
nav:
  # - Home: home.md
  - Index: index.md
  - About: about.md
site_url: https://clevinson.github.io/oae-data-protocol
repo_url: https://github.com/clevinson/oae-data-protocol
markdown_extensions:
  - tables
extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js

# Uncomment this block to enable use of Google Analytics.
# Replace the property value with your own ID.
# extra:
#   analytics:
#     provider: google
#     property: G-XXXXXXXXXX
